services:
  - type: static_site
    name: sistema-cobranca-frontend
    buildCommand: "npm install && npm run build"
    staticPublishPath: "dist"
    env:
      - key: NODE_VERSION
        value: "18"
